#!/bin/bash
### BEGIN INIT INFO
# Default-Start:	2 3 4 5
### END INIT INFO

## DECLARAÇÃO DA POLÍTICA PADRÃO: RESTRITIVA
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

## LIMPAR AS REGRAS DAS CHAINS DAS TABELAS FILTER E NAT
iptables -t filter -F
iptables -t nat -F

# HABILITAR FUNÇÃO ROTEAMENTO
echo 1 > /proc/sys/net/ipv4/ip_forward
# HABILITAR FUNÇÃO DE NAT
iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE

#### REGRA 0 ####
#### ESTADO DO PACOTE ####
#### PERMITINDO RETORNO DE TODO PACOTE QUE TEVE SUA IDA LIBERADA
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

## LIBERAR O LOCALHOST
#### Baseado em IP - 127.0.0.1
#iptables -A INPUT -s 127.0.0.1 -j ACCEPT
#iptables -A OUTPUT -d 127.0.0.1 -j ACCEPT
#### Baseado em Interface - lo
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

## LIBERAR O ACESSO DO CLIENTE TÓQUIO
#iptables -A INPUT -s 10.10.0.1 -j ACCEPT
#iptables -A OUTPUT -d 10.10.0.1 -j ACCEPT
#iptables -A FORWARD -s 10.10.0.1 -j ACCEPT
#iptables -A FORWARD -d 10.10.0.1 -j ACCEPT

## 1) LIBERAR O ACESSO SSH DO FIREWALL
#By Lucas Henrique
#iptables -A INPUT -p tcp --dport 22 -j ACCEPT
#iptables -A OUTPUT -p tcp --sport 22 -j ACCEPT
#By Victor
#iptables -A INPUT -sport 22 -p tcp -s 172.31.0.0/24 -j ACCEPT
#iptables -A OUTPUT -sport 22 -p tcp -s 172.31.0.0/24 -j ACCEPT

## 6) REJEITAR "ICMP" DO CLIENTE PARA SRVWEB-DENVER, GERANDO LOG QUANDO ACIONADO
iptables -A FORWARD -s 10.10.0.1 -d 172.31.0.253 -p icmp -j LOG --log-prefix "Tentativa frustrada de LOG"
iptables -A FORWARD -s 10.10.0.1 -d 172.31.0.253 -p icmp -j REJECT

## 2) LIBERAR O ICMP PARA TODO CENÁRIO
iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT
iptables -A FORWARD -p icmp -j ACCEPT

## 3) RESTRINGIR SSH DO SRVFW-BERLIM PARA CLIENTE, SERVIDORES E INTERNET
### Regra para o cliente
iptables -A INPUT -s 10.10.0.1 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -d 10.10.0.1 -p tcp --sport 22 -j ACCEPT
### Regra para servidoreS
iptables -A INPUT -s 172.31.0.0/24 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -d 172.31.0.0/24 -p tcp --sport 22 -j ACCEPT
### Regra para Internet
iptables -A INPUT -i enp0s3 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -o enp0s3 -p tcp --sport 22 -j ACCEPT

## 4) LIBERAR PROTOCOLO DNS
iptables -A FORWARD -p udp --dport 53 -j ACCEPT
iptables -A FORWARD -p udp --sport 53 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --sport 53 -j ACCEPT
## 5) LIBERAR REPOSITÓRIO (LINUX) VIGENTE
iptables -A OUTPUT -d deb.debian.org -j ACCEPT
iptables -A INPUT -s deb.debian.org -j ACCEPT
iptables -A OUTPUT -d security.debian.org -j ACCEPT
iptables -A INPUT -s security.debian.org -j ACCEPT
iptables -A FORWARD -d deb.debian.org -j ACCEPT
iptables -A FORWARD -s deb.debian.org -j ACCEPT
iptables -A FORWARD -d security.debian.org -j ACCEPT
iptables -A FORWARD -s security.debian.org -j ACCEPT

## 7) LIBERAR COMPARTILHAMENTO DE ARQUIVO DO SRVDC-NAIROBI
iptables -A FORWARD -d 172.31.0.252 -p tcp -m multiport --dport 139,445 -j ACCEPT
iptables -A FORWARD -s 172.31.0.252 -p tcp -m multiport --sport 139,445 -j ACCEPT
iptables -A FORWARD -d 172.31.0.252 -p udp -m multiport --dport 137,138 -j ACCEPT
iptables -A FORWARD -s 172.31.0.252 -p udp -m multiport --sport 137,138 -j ACCEPT

## 8) LIBERAR ACESSO A INTERNET (NAVEGAÇÃO); EXCETO SRVDC-NAIROBI
iptables -A FORWARD ! -s 172.31.0.252 -p tcp -m multiport --dport 80,443 -j ACCEPT
#iptables -A FORWARD ! -d 172.31.0.252 -p tcp -m multiport --sport 80,443 -j ACCEPT

## LISTAR A CONFIGURAÇÃO ATUAL
clear
iptables -L -nv --line-numbers
